services:
  api:
    build: backend
    container_name: server
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=${API_PORT:-8080}
      - DATA_PATH=${DATA_PATH:-/app/data/input.txt}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data:ro,Z
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
